In [1]:
import pandas as pd
import sqlite3

In [3]:
df = pd.read_json("importation/Projet_centres_data/SB_events/3894037.json")

C:\Users\natha\AppData\Local\Temp\ipykernel_14528\2578484759.py:1: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df = pd.read_json("importation/Projet_centres_data/SB_events/3894037.json")
C:\Users\natha\AppData\Local\Temp\ipykernel_14528\2578484759.py:1: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df = pd.read_json("importation/Projet_centres_data/SB_events/3894037.json")
C:\Users\natha\AppData\Local\Temp\ipykernel_14528\2578484759.py:1: FutureWarning: The behavior of 'to_datetime' with 'unit' when parsing strings is deprecated. In a future version, strings will be parsed as datetime strings, matching the behavior without a 'unit'. To retain the old behavior, explicitly cast ints or floats to numeric type before calling to_datetime.
  df = pd.read_json("importation/Projet_centres_data/SB_events/3894037.json")

In [5]:
df.columns.tolist()

['50_50',
 'ball_receipt_outcome',
 'ball_recovery_offensive',
 'ball_recovery_recovery_failure',
 'block_deflection',
 'block_offensive',
 'carry_end_location',
 'clearance_aerial_won',
 'clearance_body_part',
 'clearance_head',
 'clearance_left_foot',
 'clearance_other',
 'clearance_right_foot',
 'counterpress',
 'dribble_nutmeg',
 'dribble_outcome',
 'dribble_overrun',
 'duel_outcome',
 'duel_type',
 'duration',
 'foul_committed_advantage',
 'foul_committed_card',
 'foul_committed_offensive',
 'foul_committed_type',
 'foul_won_advantage',
 'foul_won_defensive',
 'goalkeeper_body_part',
 'goalkeeper_end_location',
 'goalkeeper_outcome',
 'goalkeeper_position',
 'goalkeeper_shot_saved_off_target',
 'goalkeeper_technique',
 'goalkeeper_type',
 'id',
 'index',
 'injury_stoppage_in_chain',
 'interception_outcome',
 'location',
 'match_id',
 'minute',
 'obv_against_after',
 'obv_against_before',
 'obv_against_net',
 'obv_for_after',
 'obv_for_before',
 'obv_for_net',
 'obv_total_net',
 'off_camera',
 'out',
 'pass_aerial_won',
 'pass_angle',
 'pass_assisted_shot_id',
 'pass_body_part',
 'pass_cross',
 'pass_cut_back',
 'pass_end_location',
 'pass_goal_assist',
 'pass_height',
 'pass_inswinging',
 'pass_length',
 'pass_outcome',
 'pass_outswinging',
 'pass_pass_cluster_id',
 'pass_pass_cluster_label',
 'pass_pass_cluster_probability',
 'pass_pass_success_probability',
 'pass_recipient_id',
 'pass_shot_assist',
 'pass_switch',
 'pass_technique',
 'pass_through_ball',
 'pass_type',
 'period',
 'play_pattern',
 'player_id',
 'position',
 'possession',
 'possession_team_id',
 'related_events',
 'second',
 'shot_aerial_won',
 'shot_body_part',
 'shot_deflected',
 'shot_end_location',
 'shot_first_time',
 'shot_freeze_frame',
 'shot_gk_positioning_xg_suppression',
 'shot_gk_save_difficulty_xg',
 'shot_gk_shot_stopping_xg_suppression',
 'shot_key_pass_id',
 'shot_one_on_one',
 'shot_outcome',
 'shot_saved_off_target',
 'shot_shot_execution_xg',
 'shot_shot_execution_xg_uplift',
 'shot_shot_shot_assist',
 'shot_statsbomb_xg',
 'shot_technique',
 'shot_type',
 'substitution_outcome',
 'substitution_outcome_id',
 'substitution_replacement',
 'substitution_replacement_id',
 'formation',
 'team_id',
 'timestamp',
 'type',
 'under_pressure']

In [3]:
connect = sqlite3.connect("raw-database.db")
cur = connect.cursor()

In [25]:
req = cur.execute(f"SELECT * FROM freeze_frames WHERE match_id in (1510819, 1299412, 1160044)")
res = req.fetchall()
desc = req.description
df = pd.DataFrame(res)
df.columns = [i[0] for i in desc]

ValueError: Length mismatch: Expected axis has 0 elements, new values have 10 elements

In [9]:
req = cur.execute(f"SELECT * FROM freeze_frames F JOIN events E ON F.event_id = E.id")
res = req.fetchall()
desc = req.description
df = pd.DataFrame(res)
df.columns = [i[0] for i in desc]

In [23]:
df.columns.tolist()

['frame',
 'timestamp',
 'period',
 'event_id',
 'event_x',
 'event_y',
 'is_matched',
 'match_id',
 'group',
 'tackable_object',
 'level_0',
 'id',
 'shot_type',
 'shot_outcome',
 'type',
 'match_id',
 'period',
 'possession',
 'pass_cross',
 'pass_type',
 'index_event',
 'minute',
 'pass_body_part',
 'x_loc',
 'y_loc',
 'z_loc',
 'x_pass',
 'y_pass',
 'x_shot',
 'y_shot',
 'z_shot']

In [22]:
df.sort_values("level_0")

,frame,timestamp,period,event_id,event_x,event_y,is_matched,match_id,group,tackable_object,...,minute,pass_body_part,x_loc,y_loc,z_loc,x_pass,y_pass,x_shot,y_shot,z_shot
18512,42954,2024-11-26 00:45:00.400000,2.0,fe9765b1-e672-44f7-815f-2059447cc86a,unknown,unknown,0,1518339,None,36071.0,...,45,None,NaN,NaN,None,NaN,NaN,None,None,None
16572,43538,None,NaN,f5f29ce5-9e11-465c-85ac-4c69a1b30379,unknown,unknown,0,1483175,None,28768.0,...,45,None,NaN,NaN,None,NaN,NaN,None,None,None
14134,6289,2024-11-26 00:00:10.900000,1.0,688045a5-7d09-4255-929b-e29e42029803,32.725,-21.59,1,1425163,away team,NaN,...,0,Left Foot,97.4,65.4,None,111.1,40.7,None,None,None
16828,6497,2024-11-26 00:00:10.700000,1.0,4cbfa8c3-46c5-4aec-9155-4a7b5ac8d5f6,-42.0875,-22.015,1,1488515,home team,NaN,...,0,Left Foot,108.1,14.1,None,106.2,32.3,None,None,None
18076,6615,2024-11-26 00:00:28.500000,1.0,ea788736-17d3-4151-83ba-78fbc40fe354,-50.575,25.925,0,1510823,away team,NaN,...,0,Right Foot,117.8,70.5,None,113.8,43.5,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
904,65191,2024-11-26 01:29:36.100000,2.0,55f006a5-e803-41d0-94b4-7d2c914505b5,-23.625,-6.8,1,1037621,away team,NaN,...,89,None,87.0,32.0,None,NaN,NaN,None,None,None
210,59002,2024-11-26 01:34:38.200000,2.0,11c92ba6-a3f7-4e80-8f65-c702b321f7c0,50.8375,12.41,1,1021411,home team,NaN,...,94,None,1.9,54.6,None,NaN,NaN,None,None,None
18251,29131,2024-11-26 00:38:04.100000,1.0,82a4d00f-ac58-4b8f-aa1b-8a71b62ab83c,-47.5125,2.805,0,1511013,away team,NaN,...,38,None,5.7,36.7,None,NaN,NaN,None,None,None
161,34460,2024-11-26 00:53:44,2.0,fcca62d1-ccc5-4c33-baab-c5c74d7c903a,48.475,1.02,1,1021411,away team,11080.0,...,53,None,4.6,41.2,None,NaN,NaN,None,None,None
164,35495,2024-11-26 00:55:27.500000,2.0,db409be0-21ed-4a0f-ac2e-613d459de12a,49.6125,2.805,1,1021411,home team,NaN,...,55,None,3.3,43.3,None,NaN,NaN,None,None,None