In [1]:
import pandas as pd
import sqlite3

In [2]:
freeze_frames_import = pd.read_json("importation/Projet_centres_data/SKC_crosses_freeze_frames/1020089.json")

In [3]:
freeze_frames_import

,data,possession,frame,image_corners_projection,timestamp,period,event_id,event_x,event_y,is_matched
0,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': None}",4820,"[24.17946797703396, 39.0, 9.132086207144336, -...",2024-12-06 00:04:29.000,1,54cbad0c-1f05-4708-9b7f-2cadeae0636b,35.3500,-27.710,True
1,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': 159...",4834,"[47.42111418514567, 39.0, 19.524037390543953, ...",2024-12-06 00:04:30.400,1,28239a7e-4d65-4618-99f3-2763088e5e92,42.6125,-26.860,True
2,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': None}",4854,"[42.734535236816924, 39.0, 20.253145169781963,...",2024-12-06 00:04:32.400,1,3ea6ecd9-bc39-4ce5-9b47-1eda239f2705,44.1000,1.615,True
3,[],"{'group': None, 'trackable_object': None}",5752,[],2024-12-06 00:06:02.200,1,c1a7a598-9690-4a32-a733-b7b3b585df83,-43.4000,-27.455,True
4,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': None, 'trackable_object': None}",5755,[],2024-12-06 00:06:02.500,1,d3b91062-3398-4235-8bbc-3571d2fd2d9c,-43.7500,-29.240,False
5,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'home team', 'trackable_object': None}",5796,"[-91.78848139197376, 39.0, -40.945673666515326...",2024-12-06 00:06:06.600,1,1ea8cb69-9095-4a7e-bc1a-e1ca8c4984b6,-48.8250,28.475,True
6,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'home team', 'trackable_object': None}",5946,"[-102.80394115905194, 39.0, -39.56627280863759...",2024-12-06 00:06:21.600,1,185a43ed-662b-4377-9a67-8b46c8f05a10,-49.4375,17.510,True
7,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'home team', 'trackable_object': None}",5946,"[-102.80394115905194, 39.0, -39.56627280863759...",2024-12-06 00:06:21.600,1,727c84e2-342f-4743-98f9-962c8561db59,-49.4375,17.510,True
8,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': 181...",5958,"[-102.19608161481958, 39.0, -42.15211915860544...",2024-12-06 00:06:22.800,1,fb995448-b77d-41b4-ad2e-355d2c4b0499,-41.2125,1.445,False
9,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'home team', 'trackable_object': None}",8631,"[-74.7689124458569, 39.0, -32.75217993063861, ...",2024-12-06 00:10:50.100,1,24498d51-d4eb-4b13-978d-4877c8989018,-32.9875,15.130,True
10,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'home team', 'trackable_object': None}",8657,"[-91.26985741587328, 39.0, -38.577557549541005...",2024-12-06 00:10:52.700,1,d3cc89db-8188-4d11-94c6-b7cbb5d205f3,-46.3750,24.140,True
11,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': 181...",8665,"[-93.34225469316395, 39.0, -40.13849405638299,...",2024-12-06 00:10:53.500,1,684e68e6-40b1-4e23-93d3-7bd21055ccab,-39.9875,2.295,False
12,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'home team', 'trackable_object': None}",14858,"[26.9736180476847, 39.0, 13.288647574790087, -...",2024-12-06 00:21:12.800,1,e63b578f-ddb9-40c0-8a48-ce39643755a7,50.2250,1.870,True
13,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': 8933}",14869,"[37.060809137202256, 39.0, 18.336554339574743,...",2024-12-06 00:21:13.900,1,b8ae8d8c-f681-45dc-b17b-96ad1871cf38,51.7125,-11.985,True
14,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': None}",14871,"[38.88622717118259, 39.00000000000001, 19.0996...",2024-12-06 00:21:14.100,1,6556f102-4c15-4a6b-b9ab-264a4c191e99,49.0000,-3.230,True
15,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'home team', 'trackable_object': None}",19674,"[-8.28452461233728, 39.0, -4.051967532699852, ...",2024-12-06 00:29:14.400,1,afd13fc2-9adb-4253-af0e-35de7afe26d3,17.9375,-21.930,True
16,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': 159...",19727,"[43.389436283819805, 39.0, 20.168777206655772,...",2024-12-06 00:29:19.700,1,37c2a8ba-3f35-4497-8d0c-f21a88deac11,46.3750,-16.745,True
17,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': None}",19733,"[44.23418030879166, 39.0, 21.170024118188117, ...",2024-12-06 00:29:20.300,1,5a52018d-a503-4e47-a8f9-236ecb0dcda3,47.2500,-2.380,True
18,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': 159...",21613,"[16.72442101757726, 39.0, 6.39523550617457, -2...",2024-12-06 00:32:28.300,1,ae601650-06a1-4456-bd07-8bc53a94295a,24.2375,-28.050,True
19,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': None}",21632,"[33.19685364366734, 39.0, 14.17053057730605, -...",2024-12-06 00:32:30.200,1,2b117102-f95e-4de3-902d-91b934875494,38.3250,-27.540,True
20,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': None}",21644,"[39.73702767690628, 39.0, 18.17165329675492, -...",2024-12-06 00:32:31.400,1,ea26b353-8d5b-4973-a684-1abb123cc357,44.2750,-2.720,True
21,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': 12592}",22029,"[12.23942978066822, 39.0, 6.399481599224773, -...",2024-12-06 00:33:09.900,1,eec3c8d8-4deb-4302-86fa-df565e5fa78f,39.6375,24.820,True
22,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'home team', 'trackable_object': 20395}",22052,"[29.099870009269264, 39.0, 15.857850186425903,...",2024-12-06 00:33:12.200,1,8c439fff-c1c1-48e8-a3b9-04739c95633d,46.8125,27.625,True
23,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'home team', 'trackable_object': None}",22075,"[39.79217101622434, 39.0, 21.68301399083031, -...",2024-12-06 00:33:14.500,1,b6a7eff6-b4ba-45ef-9465-c04b0b4aa09c,41.6500,-3.485,True
24,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': None}",27840,"[39.475167390722376, 38.999999999999986, 18.05...",2024-12-06 00:42:51.000,1,3b286d5a-51a0-40fe-960b-0780c48dc35a,44.8000,-24.990,True
25,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': None}",27840,"[39.475167390722376, 38.999999999999986, 18.05...",2024-12-06 00:42:51.000,1,870ea7fe-3c5c-4543-82e2-afe26bbfef7b,44.8000,-24.990,True
26,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'home team', 'trackable_object': 12327}",27860,"[41.953939631370815, 39.0, 20.91056649068584, ...",2024-12-06 00:42:53.000,1,c18d6b9e-4113-4157-a57d-aee79d0f2f51,46.5500,10.710,True
27,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': None}",33405,"[-88.14073192194225, 39.0, -37.22260788401358,...",2024-12-06 00:47:55.500,2,0c1ddf5c-5666-40ac-82f4-11d4c8d1143e,-38.5000,19.890,True
28,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': None}",33429,"[-95.31518820672309, 39.0, -42.88242081874104,...",2024-12-06 00:47:57.900,2,ff04b522-324b-430b-8ace-fc91e77554cd,-49.5250,16.320,True
29,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': None, 'trackable_object': None}",30755,"[-30.46073909908912, 39.0, -16.163842238013064...",2024-12-06 00:47:42.500,1,b94a4ca1-d637-4cfc-a6ad-4fb6f71c95c6,-11.8125,30.260,True
30,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': None}",33490,[],2024-12-06 00:48:04.000,2,c6f65551-dd30-4645-b4c1-1834d00fa74a,-46.8125,-17.680,False
31,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': None}",33502,[],2024-12-06 00:48:05.200,2,a37b848d-2f36-4287-9346-de39630cecfe,-51.5375,-15.895,True
32,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': None}",33512,"[-125.0044383933363, 39.0, -45.699060695458044...",2024-12-06 00:48:06.200,2,aea8fc44-f7b3-4f14-851e-ec1ff24c5691,-44.7125,-5.100,True
33,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'home team', 'trackable_object': 24115}",41470,"[37.845074388796164, 39.0, 17.800164928872277,...",2024-12-06 01:01:22.000,2,101d0efe-32ef-4fd2-a05a-2fe677be672c,47.1625,-20.740,True
34,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'home team', 'trackable_object': None}",41475,"[42.16338557756143, 39.000000000000014, 19.778...",2024-12-06 01:01:22.500,2,deccdb05-dc94-45df-be82-7c1516039898,49.7000,-22.525,True
35,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': None}",41488,"[44.1786292504998, 39.0, 21.204442930055503, -...",2024-12-06 01:01:23.800,2,90036fa9-8eae-4ec7-ac10-5a053e01d587,44.3625,-2.125,False
36,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'home team', 'trackable_object': 12327}",42729,"[-82.62508537726644, 39.0, -38.52199388207213,...",2024-12-06 01:03:27.900,2,ab808135-4d7c-411b-a916-0c7395a1eee4,-44.1875,17.340,True
37,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'home team', 'trackable_object': 12327}",42729,"[-82.62508537726644, 39.0, -38.52199388207213,...",2024-12-06 01:03:27.900,2,a8c19eef-4ca5-469b-9c90-a4ab9d9f192f,-44.4500,17.340,True
38,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'home team', 'trackable_object': None}",42735,"[-86.67920885505261, 39.0, -40.4532976520988, ...",2024-12-06 01:03:28.500,2,60e0aebf-4005-4fe3-b6af-a15042e905ec,-38.5875,8.500,True
39,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': 8933}",43710,"[-100.77247362267609, 39.0, -32.71301297896737...",2024-12-06 01:05:06.000,2,75a72d5d-60dd-4cae-bee6-473e440fb186,-29.3125,-22.440,True
40,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': None}",43713,"[-101.01950107525975, 39.0, -33.57455646610334...",2024-12-06 01:05:06.300,2,8847f4fc-c57a-4940-b2a9-af3c6876d64f,-29.7500,-23.120,True
41,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': None}",43726,"[-103.9980206277411, 39.0, -37.215606308590004...",2024-12-06 01:05:07.600,2,ef8ab0c6-e333-4afb-8972-12aa2e7ff247,-40.3375,2.805,True
42,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'home team', 'trackable_object': None}",49434,"[25.26767718075808, 39.0, 10.164830378444538, ...",2024-12-06 01:14:38.400,2,090df558-0ac8-4a48-8b45-ac093795b34e,43.7500,-16.320,True
43,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'home team', 'trackable_object': None}",49454,"[43.89124612751364, 39.0, 22.146139751269317, ...",2024-12-06 01:14:40.400,2,88a3d412-31bf-4bb4-a7b0-176c4ce50de3,50.3125,-10.795,True
44,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'home team', 'trackable_object': None}",49459,"[46.44593405771585, 39.0, 24.309901295821852, ...",2024-12-06 01:14:40.900,2,7c5f3427-97d5-4120-aefb-f9a427fd525b,48.8250,2.635,True
45,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'home team', 'trackable_object': None}",54367,[],2024-12-06 01:22:51.700,2,23bc7e64-c4a1-4773-9008-edc3857790e4,48.4750,-20.825,True
46,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'home team', 'trackable_object': None}",54383,"[44.006473596920706, 39.0, 20.396182868653558,...",2024-12-06 01:22:53.300,2,d9af670b-79d5-4f03-89b1-2353d44e18ad,48.3875,-19.890,True
47,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'home team', 'trackable_object': None}",54397,"[40.199688460617715, 39.00000000000001, 19.616...",2024-12-06 01:22:54.700,2,07d2c6c8-fccc-449f-97ee-50468b9f8f03,44.4500,3.825,True
48,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': None}",56744,"[-91.86253994055659, 39.0, -38.73249324198923,...",2024-12-06 01:26:49.400,2,40820401-0ebb-49db-902f-64648d3707f6,-46.8125,24.905,True
49,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': None}",56747,"[-92.66511101058322, 39.0, -39.20228226597752,...",2024-12-06 01:26:49.700,2,18d7cd87-b770-47b8-9ce2-b3e8b21479cc,-48.5625,25.160,True
50,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'home team', 'trackable_object': None}",56766,"[-100.78746270397963, 39.0, -43.66916481282109...",2024-12-06 01:26:51.600,2,a4423dd6-f261-4ab6-8ab6-61b98b262d62,-44.6250,-8.755,True
51,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': None}",58588,"[-87.81069989503864, 39.0, -34.617379449607476...",2024-12-06 01:29:53.800,2,d1a4e47f-ec21-419f-8a15-d8fd1bcf409b,-21.9625,15.980,True
52,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': None}",58601,"[-89.68510874898556, 39.0, -36.09431788947899,...",2024-12-06 01:29:55.100,2,8ee50cf4-15e4-47d9-a5fd-a6a02a6051d8,-21.9625,19.210,True
53,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': None, 'trackable_object': None}",58991,[],2024-12-06 01:30:34.100,2,f9bde630-3159-4e49-9dc3-93873bdb37ee,-47.2500,-3.400,False
54,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': None}",60025,[],2024-12-06 01:32:17.500,2,fd27139a-993f-4d60-a32f-0092ccb50463,-45.9375,-20.485,True
55,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': None}",60843,"[-120.58909490120513, 39.0, -44.74367392228608...",2024-12-06 01:33:39.300,2,515ed3cb-2f16-41a8-aadd-5eb070a5097e,-44.1000,-20.995,True
56,"[{'track_id': 12235, 'trackable_object': 12235...","{'group': 'away team', 'trackable_object': None}",60854,"[-114.83251618699892, 39.0, -45.54659858409879...",2024-12-06 01:33:40.400,2,cbc4bb3b-874f-4e48-aa96-dc311f2ec14e,-47.0750,0.680,True

In [3]:
connect = sqlite3.connect("raw-database.db")
cur = connect.cursor()

In [25]:
req = cur.execute(f"SELECT * FROM freeze_frames WHERE match_id in (1510819, 1299412, 1160044)")
res = req.fetchall()
desc = req.description
df = pd.DataFrame(res)
df.columns = [i[0] for i in desc]

ValueError: Length mismatch: Expected axis has 0 elements, new values have 10 elements

In [9]:
req = cur.execute(f"SELECT * FROM freeze_frames F JOIN events E ON F.event_id = E.id")
res = req.fetchall()
desc = req.description
df = pd.DataFrame(res)
df.columns = [i[0] for i in desc]

In [23]:
df.columns.tolist()

['frame',
 'timestamp',
 'period',
 'event_id',
 'event_x',
 'event_y',
 'is_matched',
 'match_id',
 'group',
 'tackable_object',
 'level_0',
 'id',
 'shot_type',
 'shot_outcome',
 'type',
 'match_id',
 'period',
 'possession',
 'pass_cross',
 'pass_type',
 'index_event',
 'minute',
 'pass_body_part',
 'x_loc',
 'y_loc',
 'z_loc',
 'x_pass',
 'y_pass',
 'x_shot',
 'y_shot',
 'z_shot']

In [22]:
df.sort_values("level_0")

,frame,timestamp,period,event_id,event_x,event_y,is_matched,match_id,group,tackable_object,...,minute,pass_body_part,x_loc,y_loc,z_loc,x_pass,y_pass,x_shot,y_shot,z_shot
18512,42954,2024-11-26 00:45:00.400000,2.0,fe9765b1-e672-44f7-815f-2059447cc86a,unknown,unknown,0,1518339,None,36071.0,...,45,None,NaN,NaN,None,NaN,NaN,None,None,None
16572,43538,None,NaN,f5f29ce5-9e11-465c-85ac-4c69a1b30379,unknown,unknown,0,1483175,None,28768.0,...,45,None,NaN,NaN,None,NaN,NaN,None,None,None
14134,6289,2024-11-26 00:00:10.900000,1.0,688045a5-7d09-4255-929b-e29e42029803,32.725,-21.59,1,1425163,away team,NaN,...,0,Left Foot,97.4,65.4,None,111.1,40.7,None,None,None
16828,6497,2024-11-26 00:00:10.700000,1.0,4cbfa8c3-46c5-4aec-9155-4a7b5ac8d5f6,-42.0875,-22.015,1,1488515,home team,NaN,...,0,Left Foot,108.1,14.1,None,106.2,32.3,None,None,None
18076,6615,2024-11-26 00:00:28.500000,1.0,ea788736-17d3-4151-83ba-78fbc40fe354,-50.575,25.925,0,1510823,away team,NaN,...,0,Right Foot,117.8,70.5,None,113.8,43.5,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
904,65191,2024-11-26 01:29:36.100000,2.0,55f006a5-e803-41d0-94b4-7d2c914505b5,-23.625,-6.8,1,1037621,away team,NaN,...,89,None,87.0,32.0,None,NaN,NaN,None,None,None
210,59002,2024-11-26 01:34:38.200000,2.0,11c92ba6-a3f7-4e80-8f65-c702b321f7c0,50.8375,12.41,1,1021411,home team,NaN,...,94,None,1.9,54.6,None,NaN,NaN,None,None,None
18251,29131,2024-11-26 00:38:04.100000,1.0,82a4d00f-ac58-4b8f-aa1b-8a71b62ab83c,-47.5125,2.805,0,1511013,away team,NaN,...,38,None,5.7,36.7,None,NaN,NaN,None,None,None
161,34460,2024-11-26 00:53:44,2.0,fcca62d1-ccc5-4c33-baab-c5c74d7c903a,48.475,1.02,1,1021411,away team,11080.0,...,53,None,4.6,41.2,None,NaN,NaN,None,None,None
164,35495,2024-11-26 00:55:27.500000,2.0,db409be0-21ed-4a0f-ac2e-613d459de12a,49.6125,2.805,1,1021411,home team,NaN,...,55,None,3.3,43.3,None,NaN,NaN,None,None,None